name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER --password-stdin <<< "$DOCKER_PASSWORD"
        
    - name: Get current date # get the date of the build
      id: date
      run: echo "name=date::$(date +'%Y-%m-%d--%M-%S')" >> $GITHUB_OUTPUT

    - name: Build the Docker image
      env: 
        DOCKER_BUILDKIT: 1
      run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:$GITHUB_OUTPUT
      
    - name: Docker Push
      run: docker push $DOCKER_USER/$REPO_NAME:$GITHUB_OUTPUT
